### ISSUE TITLE
Documentation structure

### ISSUE THREAD

**Issue by mthpvg** [upfrontIO/livingdocs#34]
**As a developer I want to have the basics of Livingdocs covered by documentation**

https://tracking.nzzmg.ch/browse/WCMS-3056

- [ ] clear taxonomy #36
- [ ] decide on clear structure #35 
- [ ] know the minimum list of guides #38
- [ ] describe the README content #37 
- [ ] Bonus: rename the livingodcs repository to livingdocs-documentation

This epic is finished when structure, taxonomy and readme content are documented in the guides repo

Follow up epic will be about the implementation:
- [ ] write the minimum guides
- [ ] implement that structure in the livingdocs repo
- [ ] fit in all existing documentation, delete whats unusable / outdated
- [ ] implement the structure in the project READMEs

**Comment by mthpvg** [comment]
@peyerluk: Here is the epic we discussed this morning, it contains 4 issues.

**Comment by masone** [comment]
moved to https://github.com/upfrontIO/livingdocs-planning/issues/4
